### ISSUE TITLE
Add Anaconda Cloud Google Analytics tag, activate Google Webmaster Tools

### ISSUE THREAD

**Issue by FirecatSue** [Anaconda-Server/docs.anaconda.org#197] opened 2015-11-14 12:59 UTC
Please add the Google Analytics tag to the docs.anaconda.org site.

I've set up a new Google Tag Manager container for the site. Place this code just after the opening <Body> tag.

Google Webmaster Tools: Upload the attached html file to docs.anaconda.org and notify me so I can verify that site.

[Google-Tag-Manager-Anaconda-Cloud-snippet.txt](https://github.com/Anaconda-Server/docs.anaconda.org/files/34609/Google-Tag-Manager-Anaconda-Cloud-snippet.txt)

**Comment by mistakevin** [comment] 2015-11-16 19:09
Closing, duplicate of https://github.com/Anaconda-Server/anaconda-server/issues/1011

**Closed by mistakevin** 2015-11-16 19:09 UTC
